refinando

diff --git a/.github/workflows/setup_lakehouse.yml b/.github/workflows/setup_lakehouse.yml
--- a/.github/workflows/setup_lakehouse.yml
+++ b/.github/workflows/setup_lakehouse.yml
@@ -87,6 +87,39 @@ jobs:
           name: lakehouse
           path: ${{ github.workspace }}/azsetup/lakehouse
 
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
+
+      - name: Install PyYAML
+        run: pip install pyyaml
+
+      - name: Check if YAML file exists
+        run: |
+          if [ ! -f "${{ github.workspace }}/datamaster/strife_env/strife_config.yaml" ]; then
+            echo "YAML file not found!"
+            exit 1
+          fi
+
+      - name: Read YAML file
+        id: read_yaml
+        run: |
+          python -c "
+          import yaml
+          import os
+          with open('../../datamaster/strife_env/strife_config.yaml', 'r') as stream:
+              config = yaml.safe_load(stream)
+              for key, value in config.items():
+                  print(f'::set-output name={key}::{value}')
+          "
+
+      - name: Set environment variables from YAML
+        run: |
+          echo "domain=${{ steps.read_yaml.outputs.domain }}" >> $GITHUB_ENV
+          echo "catalog=${{ steps.read_yaml.outputs.catalog }}" >> $GITHUB_ENV
+          echo "project=${{ steps.read_yaml.outputs.project }}" >> $GITHUB_ENV
+
       # Configura e inicializa o Terraform
       # Set up and initialize Terraform
       - uses: hashicorp/setup-terraform@v2
